services:
  database:
    image: postgres:15-alpine
    container_name: fetchdesk_db
    environment:
      POSTGRES_DB: fetchdesk
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: FetchDesk/Dockerfile # Caminho para o Dockerfile da API
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=database;Database=fetchdesk;Username=admin;Password=your_password
    depends_on:
      - database
    ports:
      - "5000:8080"

  frontend:
    build:
      context: .
      dockerfile: FetchDesk.Client/Dockerfile # Caminho para o Dockerfile do Blazor
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  postgres_data: